# Generated by Django 6.0.3 on 2026-03-21 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('compressed_file', models.FileField(blank=True, upload_to='compressed/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('preset', models.CharField(choices=[('screen', 'Pantalla (72 dpi) — mínimo tamaño'), ('ebook', 'eBook (150 dpi) — equilibrado'), ('printer', 'Impresora (300 dpi) — alta calidad'), ('prepress', 'Preimpresión (300 dpi) — máxima calidad')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('original_size', models.BigIntegerField(default=0)),
                ('compressed_size', models.BigIntegerField(default=0)),
                ('compression_ratio', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
