# Generated by Django 6.0.3 on 2026-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_pdfjob_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfjob',
            name='compatibility',
            field=models.CharField(choices=[('pdf-1.4', 'Máxima compatibilidad (PDF 1.4)'), ('pdf-1.5', 'Mejor compresión (PDF 1.5)'), ('pdf-1.7', 'Moderno (PDF 1.7)'), ('pdfa-2b', 'Archivado (PDF/A-2b)')], default='pdf-1.7', max_length=20),
        ),
    ]
